version: "3.1"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: taskdb
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
